# Generated by Django 5.2.8 on 2025-11-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0002_posts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
