# Generated by Django 5.2.8 on 2025-11-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0003_posts_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='body',
            new_name='content',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
